version: "3"
services:
  api:
    container_name: api
    environment:
      - PGHOST=postgres
      - PGDATABASE=thermonitor
      - PGUSER=postgres
      - PGPASSWORD=root
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    ports:
      - "8000:8000"
  engine:
    container_name: engine
    build:
      context: .
      dockerfile: ./packages/engine/Dockerfile
    ports:
      - "8001:8001"
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=thermonitor
    build:
      context: ./packages/db/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./packages/db/dumps/init.sql:/docker-entrypoint/initdb.d/init.sql
volumes:
  dumps:
