version: "3.8"
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
      - 3000:3000
  api:
    container_name: api
    env_file:
      - ./packages/api/.env
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
  account-service:
    container_name: account-service
    environment:
      - PGHOST=postgres
      - PGDATABASE=thermonitor
      - PGUSER=postgres
      - PGPASSWORD=root
    build:
      context: .
      dockerfile: ./packages/account-service/Dockerfile
    ports:
      - 8002:8002
    depends_on:
      postgres:
        condition: service_healthy
  engine:
    container_name: engine
    build:
      context: .
      dockerfile: ./packages/engine/Dockerfile
    ports:
      - 8001:8001
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=thermonitor
    build:
      context: ./packages/db/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "thermonitor", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./packages/db/dumps/:/docker-entrypoint/initdb.d/

volumes:
  dumps:
