version: "3"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "8000:80"
  engine:
    container_name: engine
    build:
      context: .
      dockerfile: packages/engine/Dockerfile
    ports:
      - "8001:80"
